import os
from fastapi import FastAPI, HTTPException
from fastapi.middleware.cors import CORSMiddleware
from pydantic import BaseModel, Field
import requests
from typing import Optional, Any, Dict

app = FastAPI()

app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

WEBHOOK_URL = "https://davedandemo.app.n8n.cloud/webhook-test/06a670b3-4a9e-4c20-90d8-8f5eb507affe"


class BuildRequest(BaseModel):
    name: Optional[str] = Field(default=None, description="Optional project name")
    brief: str = Field(min_length=5, description="Prompt describing what to build")
    target: Optional[str] = Field(default="web", description="'web' or 'mobile'")


class BuildResponse(BaseModel):
    status: str
    plan: Dict[str, Any]
    preview_html: str


@app.get("/")
def read_root():
    return {"message": "Hello from FastAPI Backend!"}


@app.get("/api/hello")
def hello():
    return {"message": "Hello from the backend API!"}


@app.get("/test")
def test_database():
    """Test endpoint to check if database is available and accessible"""
    response = {
        "backend": "✅ Running",
        "database": "❌ Not Available",
        "database_url": None,
        "database_name": None,
        "connection_status": "Not Connected",
        "collections": []
    }
    
    try:
        # Try to import database module
        from database import db
        
        if db is not None:
            response["database"] = "✅ Available"
            response["database_url"] = "✅ Configured"
            response["database_name"] = db.name if hasattr(db, 'name') else "✅ Connected"
            response["connection_status"] = "Connected"
            
            # Try to list collections to verify connectivity
            try:
                collections = db.list_collection_names()
                response["collections"] = collections[:10]  # Show first 10 collections
                response["database"] = "✅ Connected & Working"
            except Exception as e:
                response["database"] = f"⚠️  Connected but Error: {str(e)[:50]}"
        else:
            response["database"] = "⚠️  Available but not initialized"
            
    except ImportError:
        response["database"] = "❌ Database module not found (run enable-database first)"
    except Exception as e:
        response["database"] = f"❌ Error: {str(e)[:50]}"
    
    # Check environment variables
    import os
    response["database_url"] = "✅ Set" if os.getenv("DATABASE_URL") else "❌ Not Set"
    response["database_name"] = "✅ Set" if os.getenv("DATABASE_NAME") else "❌ Not Set"
    
    return response


def synthesize_preview_html(name: Optional[str], brief: str, target: str, plan: Dict[str, Any]) -> str:
    title = name or "AI FORGE Preview"
    # Simple responsive preview shell using Tailwind CDN for quick styling inside iframe
    # Note: This is sandboxed iframe content, separate from app's Tailwind build
    color = "#74ACDF"
    device_hint = "Mobile App" if target == "mobile" else "Website"
    summary = plan.get("summary") or brief[:200]
    return f"""
<!DOCTYPE html>
<html lang=\"en\">
  <head>
    <meta charset=\"UTF-8\" />
    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\" />
    <title>{title} – {device_hint}</title>
    <script src=\"https://cdn.tailwindcss.com\"></script>
  </head>
  <body class=\"min-h-screen bg-black text-white\">
    <header class=\"px-4 py-4 border-b border-white/10\">
      <h1 class=\"text-2xl font-extrabold\" style=\"color:{color}\">{title}</h1>
      <p class=\"text-white/70\">{device_hint} concept</p>
    </header>
    <main class=\"p-6 space-y-6\">
      <section class=\"rounded-xl border border-white/10 p-4 bg-white/5\">
        <h2 class=\"font-semibold mb-2\">Concept Summary</h2>
        <p class=\"text-white/80\">{summary}</p>
      </section>
      <section class=\"grid md:grid-cols-3 gap-4\">
        <div class=\"rounded-lg border border-white/10 p-4 bg-white/5\">
          <h3 class=\"font-semibold mb-1\">Primary Action</h3>
          <button class=\"mt-2 px-4 py-2 rounded-md bg-blue-600 hover:bg-blue-500\">Get Started</button>
        </div>
        <div class=\"rounded-lg border border-white/10 p-4 bg-white/5\">
          <h3 class=\"font-semibold mb-1\">Key Feature</h3>
          <p class=\"text-white/80\">Scaffolded from your prompt.</p>
        </div>
        <div class=\"rounded-lg border border-white/10 p-4 bg-white/5\">
          <h3 class=\"font-semibold mb-1\">Status</h3>
          <p class=\"text-white/80\">Interactive preview generated by AI FORGE.</p>
        </div>
      </section>
    </main>
  </body>
</html>
"""


@app.post("/api/build", response_model=BuildResponse)
def build_project(req: BuildRequest):
    # Step 1: Send to external webhook and wait for response
    payload = {
        "brand": "AI FORGE",
        "intent": "start_building",
        "timestamp": __import__("datetime").datetime.utcnow().isoformat() + "Z",
        "page": {"title": "AI FORGE Builder", "layout": "chat+preview"},
        "ui": {"hasSpline": False, "components": ["Header", "ChatPanel", "PreviewPanel", "StatusBar"]},
        "project": {"name": req.name, "brief": req.brief, "target": req.target},
    }
    try:
        wh = requests.post(WEBHOOK_URL, json=payload, timeout=20)
        wh.raise_for_status()
        webhook_data = wh.json() if wh.headers.get("content-type", "").startswith("application/json") else {"raw": wh.text}
    except Exception as e:
        # If webhook fails, proceed with a minimal plan so user can continue
        webhook_data = {"error": str(e)}
    
    # Step 2: Create a minimal build plan/summary using provided data
    plan = {
        "summary": f"Build a {req.target or 'web'} experience: {req.brief}",
        "source": "webhook" if "error" not in webhook_data else "fallback",
        "webhook": webhook_data,
    }

    # Step 3: Produce a live preview HTML artifact for the right pane
    preview_html = synthesize_preview_html(req.name, req.brief, (req.target or "web").lower(), plan)

    return BuildResponse(status="ok", plan=plan, preview_html=preview_html)


if __name__ == "__main__":
    import uvicorn
    port = int(os.getenv("PORT", 8000))
    uvicorn.run(app, host="0.0.0.0", port=port)
